### ISSUE TITLE
renkbench.de Site Down

### ISSUE THREAD

**Issue by RetroJimmyX** [lachsfilet/Workbench#9]
The http://www.renkbench.de site is down - is there another site for a demo please?

**Comment by renkman** [comment]
Hi @RetroJimmyX ,

I just triggered the CD pipeline, the website is now up and running again.

Best regards

**Comment by syxanash** [comment]
Hi @renkman any plan to bring the domain back up? This project looks amazing and I'd love to add it to a [Web Desktop collection](https://github.com/syxanash/awesome-web-desktops) that I'm curating!

**Comment by renkman** [comment]
Hi @syxanash,

the page is up and running again, thanks for adding my little Amiga Workbench clone.

Best regards
